id = "helios-theme"
name = "Helios"
description = "Helios theme for Zed"
version = "0.0.7"
schema_version = 2
authors = ["<chris@puska.org>"]
repository = "https://github.com/heliosgraphics/helios-theme"
